[versions]
agp = "8.8.1"  # Update Android Gradle Plugin
gson = "2.10.1" # Update Gson
kotlin = "1.9.23" # Update Kotlin
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
hilt = "2.51.1" # Update Hilt
room = "2.6.1"  # Update Room
ksp = "1.9.23-1.0.19" # Align KSP with Kotlin version
coroutines = "1.8.0"
constraintlayout = "2.1.4"
kotlinxSerializationJson = "1.6.3" # Add kotlinx-serialization

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.0" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" } # Use activity-ktx
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.9" }



material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#hilt
hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}

#room
room-runtime  = { group = "androidx.room", name="room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name="room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name="room-paging", version.ref = "room" }
room-compiler = { group = "androidx.room", name="room-compiler", version.ref = "room" }
room-test = { group = "androidx.room", name="room-testing", version.ref = "room" }

#coroutines
coroutines =  { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines"}

[bundles]
room = [
    "room-runtime",
    "room-ktx",
    "room-paging",
]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

hilt =  { id = "com.google.dagger.hilt.android", version.ref ="hilt"}
ksp = {  id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
